USE kei;

DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Enrollment;
DROP TABLE IF EXISTS Chapter;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS InviteCode;
DROP TABLE IF EXISTS User;

-- DROP DATABASE IF EXISTS kei;
